### ISSUE TITLE
#eggfacts Book Application

### ISSUE THREAD

**Issue by maboa** [BadIdeaFactory/corporate#42] opened 2017-10-21 09:38 UTC
# BIFFUD Project Application
As described in section 11.11.B of the BIFFUD Corporate Bylaws I hereby invoke
my rights as a sentient being who has not uploaded their mind to the cloud for consideration of this project application by the BIFFUD Hive Mind.  With this
application I submit my interest in becoming a Member of BIFFUD and having this
project supported and adored by all who can 🤔.

## Project Information
- Project Name: [The #eggfacts Book ]
- Project Haiku: 
egg and chips, eggs with
spam, egg and peas, more eggs please
eggs are round, kinda

- Project Analogy: [It's like `wikipedia` for `eggz`]

### Project Description
[What's the vision, really sell us on this thing]

We will produce and sell a delightfully illustrated counter-top book with organically sourced egg facts that will make the reader 🤔

Eggs sell themselves. We've done extensive market research and established that 66.67%* of the world's population like eggs and ergo will want to read interesting facts about them. Eggs unite the world - this book will create world peace. 

We already have a good stash of #eggfacts but will harvest more by surreptitiously adding a #eggfacts channel on ALL Slacks we possibly can, doubling as a guerilla marketing campaign, culminating in a "@channel Did you know the #eggfacts book is now available?" message, followed by a swift deletion of the channel.

Unless we manage to create #eggstarter first (see separate future application),  we'll use kickstarter to raise funds for our project.

*sample size 4

### How is this project a bad idea?

Nobody wants to read facts about eggs .... ( or do they?  🤔 ) We'll spend many egg hours harvesting #eggfacts, creating accompanying content / illustrations, establishing printing / shipping logistics,  buying eggs and writing #eggfacts on them (stretchgoals), decorating eggs with dog hair (to create unique eggcharacters - (super stretch goals)), only to sell exactly zero copies (unless we buy them ourselves).

### If this project were a D&D Character, what alignment would it be and why?
Alignment:
- [x] [Chaotic Good](http://easydamus.com/chaoticgood.html)
- [ ] [Neutral Good](http://easydamus.com/neutralgood.html)
- [ ] [Chaotic Neutral](http://easydamus.com/chaoticneutral.html)

Don't know? [This might help](https://www.google.com/search?q=D%26D+alignment+tables) <-- this doesn't help.

### Where are the lulz?
Are you kidding?

### How does this project make people thinking face emoji?
:Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg::Reggaegg:

### Who is involved?
Eggroller1
- Name: Mark 'The Eggshark' Boas
- Twitter: @maboa
- Github ID: maboa
- Skillz: don't mind if I do
- Project role / expectations: will scramble to make #eggfacts incarnate
- Project stake: 50%

Eggroller2
- Name: Chris '#eggfacts' Zubak-Skees
- Twitter: @zubakskees
- Github ID: zubakskees
- Skillz: yes please
- Project role / expectations: chief #eggfact poacher
- Project stake: 50%

### Who will be the project's Comptroller?
Eggshark Boas or Chris #eggfacts (if there must be one) - I'm invisaging a double-yolk approach.

### Is this realistic to implement via BIFFUD?
Eggsactly! :Reggaegg:

## Next Steps
Please attend the next scheduled BIFFUD plotting session to plead your case.
This issue will be updated with application status and next steps.

**Comment by chriszs** [comment] 2017-10-21 12:55
![:Reggaegg:](http://78.media.tumblr.com/2d24e1fb1e0f68bfc65128a042c127b3/tumblr_npzuw1FFvb1s0wiloo1_400.gif)

**Comment by chriszs** [comment] 2017-10-21 14:40
(Gif by Steph Davidson/Bloomberg. Most egg facts copyright Wikipedia contributors, licensed [Creative Commons Attribution-ShareAlike License](https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License). Special thanks to original egg-facter @knowtheory.)

**Comment by chriszs** [comment] 2017-10-21 18:36
Approved at October 21, 2017 plotting session. Questions from memory:
- Is a budget needed? To be addressed in later plotting sessions.
- Do you need egg fact checkers, e.g. eggheads to verify your facts? Mark and I will be checking the facts but may enlist help.
- Can we partner with Snopes to get our egg facts checked? Can have partner discussions, want to check with them first.
- What's the plan? 1. Develop marketing materials. 2. Kickstarter preorder campaign. 3. Collect and illustrate facts. 4. Print-on-demand.
- Will the facts come from the #eggfacts channel? How many original facts? Some will come from the channel. Will also be sourcing original facts.
- What's the IP status of the channel? Most facts from Wikipedia, licensed CC Attribution-ShareAlike. Will need to check facts, rewrite to meet high standards readers expect from @BadIdeaFactory.
- Will you have one fact per page? Yes.

**Comment by slifty** [comment] 2017-11-12 16:57
Before the issue is closed the team will need to agree on an ownership breakdown and sign an ownership contract, at which point the ball gets rollin for real!

**Closed** 2019-01-19 01:49 UTC
Labels: APPROVED, project application
